#!/usr/bin/env python3
"""Build a static OCOS package registry from every pkg-src/*/ directory.

Layout produced:
    dist/registry/
        index.cfg                          -- list of all packages
        <id>/<version>/manifest.cfg
        <id>/<version>/<files-from-manifest>

The OCOS pkg client (`lib/pkg/registry.lua`) fetches `<base>/index.cfg`
to discover packages, then `<base>/<id>/<version>/manifest.cfg` and
each declared file via HTTP. Hosting this layout on GitHub Pages or
raw.githubusercontent.com makes `pkg install ocos.robot` work for
anyone who has the canonical OCOS registry configured (the default).

Each package is built by delegating to pack.py — that script already
knows how to honour `include` globs, copy declared files, and emit a
sha256-stamped manifest. We just call it once per pkg-src dir.
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PKG_SRC = REPO / "pkg-src"
DEFAULT_OUT = REPO / "dist" / "registry"


def lua_str(s: str) -> str:
    return '"' + (s or "").replace("\\", "\\\\").replace('"', '\\"') + '"'


def grab(body: str, name: str) -> str:
    m = re.search(rf'{name}\s*=\s*"([^"]*)"', body)
    return m.group(1) if m else ""


def read_meta(manifest_path: Path) -> dict:
    text = manifest_path.read_text(encoding="utf-8")
    # Strip line comments so they can't confuse the regexes.
    text = re.sub(r"--[^\n]*", "", text)
    return {
        "id":          grab(text, "id"),
        "version":     grab(text, "version"),
        "name":        grab(text, "name"),
        "description": grab(text, "description"),
    }


def build_one(src: Path, out_base: Path) -> dict:
    meta = read_meta(src / "manifest.cfg")
    if not meta["id"] or not meta["version"]:
        print(f"registry: {src} missing id/version — skipped", file=sys.stderr)
        return {}
    target = out_base / meta["id"] / meta["version"]
    target.mkdir(parents=True, exist_ok=True)
    rc = subprocess.call([sys.executable, str(REPO / "tools" / "pack.py"),
                          str(src), "-o", str(target)])
    if rc != 0:
        print(f"registry: pack.py failed for {src}", file=sys.stderr)
        sys.exit(rc)
    return meta


def write_index(out_base: Path, packages: list[dict]) -> None:
    lines = [
        "-- /dist/registry/index.cfg — auto-generated by tools/build-registry.py",
        "-- Lists every package available in this registry. Used by the OCOS",
        "-- client to resolve `pkg install <id>` to a base URL + version.",
        "return {",
        "  packages = {",
    ]
    for p in sorted(packages, key=lambda x: x["id"]):
        lines.append("    {")
        lines.append(f"      id          = {lua_str(p['id'])},")
        lines.append(f"      version     = {lua_str(p['version'])},")
        lines.append(f"      name        = {lua_str(p['name'])},")
        lines.append(f"      description = {lua_str(p['description'])},")
        lines.append("    },")
    lines.append("  },")
    lines.append("}")
    lines.append("")
    (out_base / "index.cfg").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--out", default=str(DEFAULT_OUT),
                   help="registry root directory (default: dist/registry)")
    args = p.parse_args()
    out_base = Path(args.out).resolve()
    out_base.mkdir(parents=True, exist_ok=True)

    if not PKG_SRC.exists():
        print(f"registry: no pkg-src/ at {PKG_SRC}", file=sys.stderr)
        return 1

    packages = []
    for child in sorted(PKG_SRC.iterdir()):
        if not child.is_dir() or not (child / "manifest.cfg").exists():
            continue
        meta = build_one(child, out_base)
        if meta:
            packages.append(meta)

    if not packages:
        print("registry: no packages found", file=sys.stderr)
        return 1

    write_index(out_base, packages)
    print(f"registry: wrote {out_base} ({len(packages)} packages)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
