#!/usr/bin/env python3
"""Pack the OCOS source tree into a single self-contained installer.lua.

The installer is meant to be wgot/copied onto an OpenComputers machine
running OpenOS (or any other Lua OS that exposes the standard
`component`/`computer` globals plus a writable filesystem). When invoked
it writes every OCOS file onto the chosen target disk, then optionally
sets that disk's address as the bootable one.

Output format
-------------
Each file becomes a single `W(path, [=[...content...]=])` call where the
long-bracket level is chosen to avoid colliding with the file's own
content. A header bundles the helper functions; a footer drives the
install. The whole thing is one Lua chunk, deterministic, with no
external dependencies.

Usage
-----
    tools/build-installer.py [--out dist/ocos-installer.lua]
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


HEADER = r"""-- OCOS self-installer. Generated by tools/build-installer.py.
-- Run from any Lua OS that exposes the standard `component`/`computer`
-- globals plus a writable filesystem; the script picks a target disk,
-- writes every OCOS file onto it, and (with consent) sets it as bootable.
--
-- Usage on OpenOS:
--   wget <url>/ocos-installer.lua /tmp/ocos.lua
--   /tmp/ocos.lua [target-fs-address-prefix]
--
-- The optional argument selects the destination filesystem by an address
-- prefix (the first 4–8 chars are usually enough). When omitted, the
-- script lists candidates and prompts.

local args = { ... }
local invoke = component.invoke

local function eprint(s) io.stderr:write(s .. "\n") end
local function ok(s)     io.write("[ok] "   .. s .. "\n") end
local function warn(s)   io.write("[warn] " .. s .. "\n") end

-- ---- target selection --------------------------------------------------

local function list_writable()
  local out = {}
  for addr, _ in component.list("filesystem") do
    local rok, ro = pcall(invoke, addr, "isReadOnly")
    if rok and not ro then
      local label = (pcall(invoke, addr, "getLabel") and invoke(addr, "getLabel")) or ""
      out[#out + 1] = { addr = addr, label = label,
                        free = invoke(addr, "spaceTotal") - invoke(addr, "spaceUsed") }
    end
  end
  return out
end

local function pick_target()
  local boot = computer.getBootAddress and computer.getBootAddress()
  local cands = {}
  for _, fs in ipairs(list_writable()) do
    if fs.addr ~= boot then cands[#cands + 1] = fs end
  end
  if #cands == 0 then return nil, "no writable non-boot filesystem found" end
  if args[1] then
    for _, fs in ipairs(cands) do
      if fs.addr:sub(1, #args[1]) == args[1] then return fs end
    end
    return nil, "no writable disk matches prefix '" .. args[1] .. "'"
  end
  if #cands == 1 then return cands[1] end
  io.write("Multiple writable disks found; pass the address prefix as the\n")
  io.write("first argument to pick one:\n")
  for _, fs in ipairs(cands) do
    io.write(string.format("  %s  (%s, %d bytes free)\n",
      fs.addr:sub(1, 8), fs.label ~= "" and fs.label or "<unlabelled>", fs.free))
  end
  return nil, "ambiguous target"
end

-- ---- write helpers -----------------------------------------------------

local function ensure_dir(addr, path)
  -- Walk the path, creating each missing intermediate directory.
  local parts, cur = {}, ""
  for p in path:gmatch("[^/]+") do parts[#parts + 1] = p end
  for i = 1, #parts - 1 do
    cur = cur .. "/" .. parts[i]
    local ok_e, exists = pcall(invoke, addr, "exists", cur)
    if ok_e and not exists then pcall(invoke, addr, "makeDirectory", cur) end
  end
end

local count, target_addr = 0, nil

local function W(path, content)
  ensure_dir(target_addr, path)
  local h, err = invoke(target_addr, "open", path, "w")
  if not h then eprint("write " .. path .. ": " .. tostring(err)); return end
  invoke(target_addr, "write", h, content)
  invoke(target_addr, "close", h)
  count = count + 1
end

-- ---- main --------------------------------------------------------------

local target, err = pick_target()
if not target then eprint("install: " .. err); return 1 end
target_addr = target.addr
ok("installing OCOS to " .. target_addr:sub(1, 8) ..
   " (" .. (target.label ~= "" and target.label or "<unlabelled>") .. ")")

-- Files follow.
"""


FOOTER = r"""

ok(string.format("wrote %d files", count))

-- Mark the target disk as the boot device (best-effort; the user can
-- always undo this with `eeprom -d` from OpenOS or by re-flashing).
local eeprom = component.list("eeprom")()
if eeprom and computer.setBootAddress then
  computer.setBootAddress(target_addr)
  ok("set boot address to " .. target_addr:sub(1, 8))
end

ok("done. Reboot to start OCOS.")
return 0
"""


def lowest_safe_bracket(content: str) -> str:
    """Return a long-bracket level (string of '=' chars) that's not in the
    content as either an opening or closing form. Lua allows arbitrary
    levels; we just need one that doesn't collide."""
    for level in range(0, 32):
        eq = "=" * level
        if f"]{eq}]" not in content:
            return eq
    raise RuntimeError("could not find a non-colliding bracket level")


def emit_file(out, abs_path: Path, rel_path: str) -> None:
    content = abs_path.read_text(encoding="utf-8")
    eq = lowest_safe_bracket(content)
    # Lua long-strings ignore an immediately-following newline; we add one
    # so the rendered chunk is readable.
    out.write(f'W({rel_path!r}, [{eq}[\n{content}]{eq}])\n')


def collect(root: Path) -> list[tuple[Path, str]]:
    out = []
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        rel = "/" + str(path.relative_to(root)).replace("\\", "/")
        out.append((path, rel))
    return out


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--out", default="dist/ocos-installer.lua")
    p.add_argument("--src", default="src")
    args = p.parse_args()

    src_root = Path(args.src).resolve()
    out_path = Path(args.out).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)

    files = collect(src_root)
    with out_path.open("w", encoding="utf-8") as out:
        out.write(HEADER)
        for abs_path, rel_path in files:
            emit_file(out, abs_path, rel_path)
        out.write(FOOTER)

    size = out_path.stat().st_size
    print(f"wrote {out_path} ({len(files)} files, {size} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
